name: Pro-Essential
main: cn.szzxol.pro.essential.Essential
version: 1.0.5
author: I_promise
commands:
   ess:
      description: Pro-Essential插件命令
      usage: /ess
   back:
      description: Pro-Essential插件命令
      usage: /back
   fly:
      description: Pro-Essential插件命令
      usage: /fly
   gm:
      description: Pro-Essential插件命令
      usage: /gm
   home:
      description: Pro-Essential插件命令
      usage: /home
   sethome:
      description: Pro-Essential插件命令
      usage: /sethome
   heal:
      description: Pro-Essential插件命令
      usage: /heal
   sespawn:
      description: Pro-Essential插件命令
      usage: /setspawn
   spawn:
      description: Pro-Essential插件命令
      usage: /spawn
   speed:
      description: Pro-Essential插件命令
      usage: /speed
   tp:
      description: Pro-Essential插件命令
      usage: /tp
   tpa:
      description: Pro-Essential插件命令
      usage: /tpa
   tpall:
      description: Pro-Essential插件命令
      usage: /tpall
   tpaccept:
      description: Pro-Essential插件命令
      usage: /tpaccepy
   tpahere:
      description: Pro-Essential插件命令
      usage: /tpahere
   tpdeny:
      description: Pro-Essential插件命令
      usage: /tpdeny
   tphere:
      description: Pro-Essential插件命令
      usage: /tphere
   sun:
      description: Pro-Essential插件命令
      usage: /sun
   rain:
      description: Pro-Essential插件命令
      usage: /rain
   invsee:
      description: Pro-Essential插件命令
      usage: /invsee
   day:
      description: Pro-Essential插件命令
      usage: /day
   night:
      description: Pro-Essential插件命令
      usage: /night
   exp:
      description: Pro-Essential插件命令
      usage: /exp
      aliases: [experience]
   level:
      description: Pro-Essential插件命令
      usage: /level
       